[
    {
        "type": "Fuel Type",
        "methods": [
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 63 tonnes C/ha; Harvest/Maturity Cycle = 30 yr",
                "co2Factor": null,
                "ch4Factor": 2.1,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Temperate (all moisture regimes)"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 9 tonnes C/ha; Harvest/Maturity Cycle = 5 yr",
                "co2Factor": null,
                "ch4Factor": 1.8,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, dry"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 21 tonnes C/ha; Harvest/Maturity Cycle = 8 yr",
                "co2Factor": null,
                "ch4Factor": 2.6,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, moist"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 50 tonnes C/ha; Harvest/Maturity Cycle = 5 yr",
                "co2Factor": null,
                "ch4Factor": 10,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, wet"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 63 tonnes C/ha; Harvest/Maturity Cycle = 30 yr",
                "co2Factor": null,
                "ch4Factor": 63,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Temperate (all moisture regimes)"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 9 tonnes C/ha; Harvest/Maturity Cycle = 5 yr",
                "co2Factor": null,
                "ch4Factor": 9,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, dry"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 21 tonnes C/ha; Harvest/Maturity Cycle = 8 yr",
                "co2Factor": null,
                "ch4Factor": 21,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, moist"
            },
            {
                "sourceOfEmission": "Aboveground biomass carbon stock at harvest = 50 tonnes C/ha; Harvest/Maturity Cycle = 5 yr",
                "co2Factor": null,
                "ch4Factor": 50,
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Tropical, wet"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical high",
                "co2Factor": null,
                "ch4Factor": "41 (29-53)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Africa"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical low",
                "co2Factor": null,
                "ch4Factor": "70.5 (39-102)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "South America"
            },
            {
                "sourceOfEmission": "Eco-region: Dry lowlands",
                "co2Factor": null,
                "ch4Factor": "117.0 (39-195)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "South America"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical",
                "co2Factor": null,
                "ch4Factor": "120.0 (12-228)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Southeast Asia"
            },
            {
                "sourceOfEmission": "Eco-region: Dry lowlands",
                "co2Factor": null,
                "ch4Factor": "75.0 (68-81)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Southeast Asia"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical",
                "co2Factor": null,
                "ch4Factor": "39.5 (28-51)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Australia"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical high",
                "co2Factor": null,
                "ch4Factor": "143.5 (133-154)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "North America"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical low",
                "co2Factor": null,
                "ch4Factor": "151.0 (104-198)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "North America"
            },
            {
                "sourceOfEmission": "Eco-region: Dry lowlands",
                "co2Factor": null,
                "ch4Factor": "132.5 (90-175)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "North America"
            },
            {
                "sourceOfEmission": "Eco-region: Humid tropical low",
                "co2Factor": null,
                "ch4Factor": "16.5 (15-18)",
                "n2oFactor": null,
                "baseUnit": "ha/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "tonnes C",
                "n2oUnit": "kgN₂O",
                "type": "Asia"
            }
        ],
        "scope": "scope1",
        "typeOfEmission": "Cropland",
        "category": "Land Use, Land Use Change and Forestry (LULUCF)",
        "categoryKey": "category",
        "nameKey": "fuelType",
        "sourceType": "Fuel Type"
    },
]