[
    {
        "type": "Fuel Type",
        "methods": [
            {
                "sourceOfEmission": "Animal category: Buffalo (liveweight = 300 kg)",
                "co2Factor": null,
                "ch4Factor": 55,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Sheep (liveweight = 65 kg)",
                "co2Factor": null,
                "ch4Factor": 8,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Goats (liveweight = 40 kg)",
                "co2Factor": null,
                "ch4Factor": 5,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Camels (liveweight = 570 kg)",
                "co2Factor": null,
                "ch4Factor": 46,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Horses (liveweight = 550 kg)",
                "co2Factor": null,
                "ch4Factor": 18,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Mules and Asses (liveweight = 245 kg)",
                "co2Factor": null,
                "ch4Factor": 10,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Deer (liveweight = 120 kg)",
                "co2Factor": null,
                "ch4Factor": 20,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Alpacas (liveweight = 65 kg)",
                "co2Factor": null,
                "ch4Factor": 8,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Swine",
                "co2Factor": null,
                "ch4Factor": 1.5,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developed country"
            },
            {
                "sourceOfEmission": "Animal category: Buffalo (liveweight = 300 kg)",
                "co2Factor": null,
                "ch4Factor": 55,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Sheep (liveweight = 45 kg)",
                "co2Factor": null,
                "ch4Factor": 5,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Goats (liveweight = 40 kg)",
                "co2Factor": null,
                "ch4Factor": 5,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Camels (liveweight = 570 kg)",
                "co2Factor": null,
                "ch4Factor": 46,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Horses (liveweight = 550 kg)",
                "co2Factor": null,
                "ch4Factor": 18,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Mules and Asses (liveweight = 245 kg)",
                "co2Factor": null,
                "ch4Factor": 10,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Deer (liveweight = 120 kg)",
                "co2Factor": null,
                "ch4Factor": 20,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Alpacas (liveweight = 65 kg)",
                "co2Factor": null,
                "ch4Factor": 8,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Swine",
                "co2Factor": null,
                "ch4Factor": 1,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Country type: Developing country"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 128,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: North America"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 53,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: North America"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 117,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Western Europe"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 57,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Western Europe"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 99,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Eastern Europe"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 58,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Eastern Europe"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 100,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Oceania"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 60,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Oceania"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 72,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Latin America"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 56,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Latin America"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 68,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Asia"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 47,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Asia"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 46,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Africa and Middle East"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 31,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Africa and Middle East"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Dairy)",
                "co2Factor": null,
                "ch4Factor": 58,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Indian Subcontinent"
            },
            {
                "sourceOfEmission": "Animal category: Cattle (Other Cattle)",
                "co2Factor": null,
                "ch4Factor": 27,
                "n2oFactor": null,
                "baseUnit": "head/yr",
                "source": "IPCC",
                "urlName": "IPCC Emission Factor Database",
                "sheetName": "output.xls",
                "file": "/upload/ef/output.xls",
                "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
                "year": "2014",
                "emissionUnit": "kgCO₂",
                "ch4Unit": "kgCH₄",
                "n2oUnit": "kgN₂O",
                "type": "Region: Indian Subcontinent"
            }
        ],
        "scope": "scope1",
        "typeOfEmission": "Enteric Fermentation",
        "category": "Land Use, Land Use Change and Forestry (LULUCF)",
        "categoryKey": "category",
        "nameKey": "fuelType",
        "sourceType": "Fuel Type"
      },  
]