[
    {
        "type": "Fuel Type",
        "methods": [
          {
            "sourceOfEmission": "Peak above-ground biomass = 1.7 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 8.5,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: boreal - dry and wet"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 1.7 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 6.5,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: cold temperate - dry"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 2.4 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 13.6,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: cold temperate - wet"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 1.6 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 6.1,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: warm temperate - dry"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 2.7 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 13.5,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: warm temperate - wet"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 2.3 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 8.7,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: tropical - dry"
          },
          {
            "sourceOfEmission": "Peak above-ground biomass = 6.2 tonnes d.m./ha Data for standing biomass are compiled from multi-year averages reported at grassland sites registered in the ORNL DAAC NPP database [http://www.daacsti.ornl.gov/NPP/].",
            "co2Factor": null,
            "ch4Factor": 16.1,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "t dm",
            "n2oUnit": "kgN₂O",
            "type": "IPCC Climate Zone: tropical - moist and wet"
          }
        ],
        "scope": "scope1",
        "typeOfEmission": "Land Converted to Grassland",
        "category": "Land Use, Land Use Change and Forestry (LULUCF)",
        "categoryKey": "category",
        "nameKey": "fuelType",
        "sourceType": "Fuel Type"
    }
]