[
    {
        "type": "Fuel Type",
        "methods": [
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: North America"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: North America"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: North America"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Western Europe"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Western Europe"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Western Europe"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Eastern Europe"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Eastern Europe"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Eastern Europe"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Oceania"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Oceania"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Oceania"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Latin America"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Latin America"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Latin America"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Africa"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Africa"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Africa"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Middle East"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Middle East"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Middle East"
          },
          {
            "sourceOfEmission": "Animal category: Mink and Polecat",
            "co2Factor": null,
            "ch4Factor": 4.59,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Asia"
          },
          {
            "sourceOfEmission": "Animal category: Rabbits",
            "co2Factor": null,
            "ch4Factor": 8.1,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Asia"
          },
          {
            "sourceOfEmission": "Animal category: Fox and Racoon",
            "co2Factor": null,
            "ch4Factor": 12.09,
            "n2oFactor": null,
            "baseUnit": "head/yr",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "kgN",
            "n2oUnit": "kgN₂O",
            "type": "Region: Asia"
          }
        ],
        "scope": "scope1",
        "typeOfEmission": "Manure Management",
        "category": "Land Use, Land Use Change and Forestry (LULUCF)",
        "categoryKey": "category",
        "nameKey": "fuelType",
        "sourceType": "Fuel Type"
      },
]