[
    {
        "type": "Fuel Type",
        "methods": [
          {
            "sourceOfEmission": "Peat type: nutrient poor",
            "co2Factor": null,
            "ch4Factor": "0.2 (0 - 0.63)",
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "boreal and temperate"
          },
          {
            "sourceOfEmission": "Peat type: nutrient rich",
            "co2Factor": null,
            "ch4Factor": "1.1 (0.03 - 2.9)",
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "boreal and temperate"
          },
          {
            "sourceOfEmission": "Peat type: Nutrient poor",
            "co2Factor": null,
            "ch4Factor": 0.07,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Boreal and Temperate"
          },
          {
            "sourceOfEmission": "Peat type: Nutrient rich",
            "co2Factor": null,
            "ch4Factor": 0.24,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Boreal and Temperate"
          },
          {
            "sourceOfEmission": "Peat type: Tropical humus",
            "co2Factor": null,
            "ch4Factor": 0.26,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Tropical"
          },
          {
            "sourceOfEmission": "Peat type: Nutrient poor",
            "co2Factor": null,
            "ch4Factor": 0.45,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Boreal and Temperate"
          },
          {
            "sourceOfEmission": "Peat type: Nutrient rich",
            "co2Factor": null,
            "ch4Factor": 0.4,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Boreal and Temperate"
          },
          {
            "sourceOfEmission": "Peat type: Tropical humus",
            "co2Factor": null,
            "ch4Factor": 0.34,
            "n2oFactor": null,
            "baseUnit": "ha",
            "source": "IPCC",
            "urlName": "IPCC Emission Factor Database",
            "sheetName": "output.xls",
            "file": "/upload/ef/output.xls",
            "link": "https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=3&ipcc_level=0",
            "year": "2014",
            "emissionUnit": "kgCO₂",
            "ch4Unit": "tonnes C",
            "n2oUnit": "kgN₂O",
            "type": "Climate zone: Tropical"
          }
        ],
        "scope": "scope1",
        "typeOfEmission": "Wetlands",
        "category": "Land Use, Land Use Change and Forestry (LULUCF)",
        "categoryKey": "category",
        "nameKey": "fuelType",
        "sourceType": "Fuel Type"
    }
]